apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: build

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  java-build:
    steps:
      - name: checkout
        uses: cloudbees-io/checkout@v1
      - name: gradle build
        uses: docker://gradle:8.6-jdk21-alpine
        run: ./gradlew build
      #- name: gradle test
      #  uses: docker://gradle:8.6-jdk21-alpine
      #  run: ./gradlew test
      #- name: sonar-scan
      #  uses: docker://gradle:8.6-jdk21-alpine
      #  run: ./gradlew sonar -Dsonar.token=${{ secrets.SONAR_TOKEN }}
      - name: build docker image
        uses: docker://gradle:8.6-jdk21-alpine
        run: ./gradlew bootBuildImage -DTAGGED_VERSION="${{  cloudbees.ref_name }}"